### ISSUE TITLE
Tries to use https:// even though I specify tcp://

### ISSUE THREAD

**Issue by explodingcamera** [ory/dockertest#105]
Thank you for this great Project!
Sadly, connecting to docker recently stopped working for me.
Docker sets my `DOCKER_HOST` to `tcp://127.0.0.1:2375` and now when I try to run my tests, dockertest tries to connect using https.
```
Could not start resource: : Post https://127.0.0.1:2375/images/create?fromImage=postgres&tag=10.0-alpine: http: server gave HTTP response to HTTPS clientFAIL
```

I'm currently running Docker 17.09.1-ce on Windows.

Also, shouldn't this only use `https` if in https://github.com/ory/dockertest/blob/v3/dockertest.go#L104 `DOCKER_CERT_PATH` has a value?

**Comment by aeneasr** [comment]
Good question, from the code it looks like that should be done in the underlying library, as we only pass the endpoint variable to the client instantiation. Could you maybe check if the added the possibility to connect through tcp instead of http?

**Comment by aeneasr** [comment]
So I checked, while docker says that it's exposing on `tcp://` the api is still REST so it's http. Are you sure you expose the legacy endpoint for this?

![image](https://user-images.githubusercontent.com/3372410/34262691-5c79362a-e66d-11e7-80f0-0aa0a243f749.png)

**Comment by explodingcamera** [comment]
Yeah, I'm exposing the legacy endpoint. The tcp:// is just some weird docker convention, it just specifies that they do either http or https over tcp/ip.
It's just that when specifying docker's displayed `tcp://localhost:2375`, dockertest shouldn't default to https like it currently does but to just pass the endpoint to the underlying library.

Currently everything that's not http:// or unix:// just creates a NewTLSPool no matter what.

I think you just need to change 
https://github.com/ory/dockertest/blob/v3/dockertest.go#L104
to `if os.Getenv("DOCKER_CERT_PATH") != "" && shouldPreferTls(endpoint) {`
because it only needs to do TLS automatically if DOCKER_CERT_PATH actually exists

**Comment by tschaub** [comment]
I've been running into the same issues.  Things work well with my local docker install on OSX.  I'm not having any luck getting the same tests to run in our CI environment where `DOCKER_HOST=tcp://172.X.X.X:2375`.  I assumed this had to do with the insecure-registries setting, but I haven't had any luck updating that either.

**Comment by tschaub** [comment]
The change suggested by @explodingcamera does look right.
```diff
--- a/dockertest.go
+++ b/dockertest.go
@@ -101,7 +101,7 @@ func NewPool(endpoint string) (*Pool, error) {
                }
        }
 
-       if os.Getenv("DOCKER_CERT_PATH") == "" && shouldPreferTls(endpoint) {
+       if os.Getenv("DOCKER_CERT_PATH") != "" && shouldPreferTls(endpoint) {
                return NewTLSPool(endpoint, os.Getenv("DOCKER_CERT_PATH"))
        }
 ```

This has gotten me one step closer.  Next up (perhaps unrelated to this lib):
```
dial tcp 127.0.0.1:32768: getsockopt: connection refused
```

**Comment by tschaub** [comment]
See #106 for @explodingcamera's proposed change.
