### ISSUE TITLE
Replace docker backend with containerd

### ISSUE THREAD

**Issue by johanbrandhorst** [ory/dockertest#111]
Hi!

I've just watched a talk about containerd at FOSDEM and it seems to me that it should be possible to replace the docker backend with containerd, for a much neater dependency stack and call stack. I realise this might have to be done in a fork, but is this something you would consider?

**Comment by aeneasr** [comment]
If containerd is fully compatible with docker and works similarly out of the box, then yes.

Another possibility would be to remove `go-dockerclient` which has direct dependencies to docker (although it's only using its HTTP API) and write HTTP calls manually, which would achieve the same as you mentioned, but with even less dependencies (actually zero dependencies)

**Comment by johanbrandhorst** [comment]
I'm not sure about API compatibility, but I would be hugely in favor of removing the Moby transative dependency.

**Comment by aeneasr** [comment]
If it's not compatible it's not an option, most people rely on Docker and it appears that containerd is not working on OSX (at least OSX isn't mentioned on their website).

Removing moby is possible by replacing go-dockerclient with something that doesn't depend on moby to interact with the API.
