### ISSUE TITLE
Container networking

### ISSUE THREAD

**Issue by ghost** [ory/dockertest#118]
Hello there,

I'm trying to use this library as a replacement for docker-compose but I'm failing to see how I can connect two containers to the same network so that they can talk to each other without host port mappings. Is this use case accounted for already?

**Comment by aeneasr** [comment]
> I'm trying to use this library as a replacement for docker-compose

That's not really the intention of this library, I think what you're looking for is this: https://github.com/fsouza/go-dockerclient

**Comment by ghost** [comment]
Sorry for the misunderstanding. I am writing integration tests where the tests are run in one container and the backing service is in another. I want to use this library to orchestrate the starting and stopping of these in the right order, etc.

Would you say this isn’t the right fit?

**Comment by aeneasr** [comment]
Depends, if you want to run the containers from within your Go tests instead of with e.g. `make`, then you could probably use this library. The real intention here however is to boot up a database or 3rd party service that you run your code against.

**Comment by ghost** [comment]
@arekkas: Thanks, it doesn't seem like the ideal fit.
