### ISSUE TITLE
Vendoring issue when importing from gopkg.in

### ISSUE THREAD

**Issue by calvn** [ory/dockertest#123]
I am seeing vendoring issues after the dockerclient package was moved internally. Vendoring is done with govendor and the import is based off gopkg.in.

```
package github.com/hashicorp/vault/builtin/logical/mysql (test)
	imports gopkg.in/ory-am/dockertest.v3
	imports github.com/ory/dockertest/docker: cannot find package "github.com/ory/dockertest/docker" in any of:
	/Users/cleung/go/src/github.com/hashicorp/vault/vendor/github.com/ory/dockertest/docker (vendor tree)
	/usr/local/Cellar/go/1.10.1/libexec/src/github.com/ory/dockertest/docker (from $GOROOT)
	/Users/cleung/go/src/github.com/ory/dockertest/docker (from $GOPATH)
FAIL	github.com/hashicorp/vault/builtin/logical/mysql [setup failed]
```

The package is also not able to be downloaded with `go get`
```
go get -d github.com/ory/dockertest/docker
package github.com/ory/dockertest/docker: cannot find package "github.com/ory/dockertest/docker" in any of:
	/usr/local/Cellar/go/1.10.1/libexec/src/github.com/ory/dockertest/docker (from $GOROOT)
	/Users/cleung/go/src/github.com/ory/dockertest/docker (from $GOPATH)
```

I think the issue might be that `package docker` is not an actual fetch-able package so anything that is external to dockertest will not be able to resolve dockertest/docker.

**Comment by aeneasr** [comment]
Yeah, please don't use gopkg.in any more. The `ory-am` domain is also deprecated. Switch to glide or dep.

**Comment by calvn** [comment]
I know that this migration was done due to https://github.com/ory/dockertest/pull/122 so that you reduce the amount of dependencies, but I think you can do the same if you kept the external dependencies, and then did a `dep prune`. This way the vendored directory would only contain the minimal amount of packages used, getting rid of docker-swarm and such.

**Comment by calvn** [comment]
Right, but even if I switched to using github.com directly, the package wouldn't get resolved (as shown by the `go get` command).

**Comment by aeneasr** [comment]
No, that would not have worked because go-dockerclient has a dependency on docker swarm which greatly increased the amount of dependencies pulled.

In the project that requires dockertest, add

```
[[constraint]]
  name = "github.com/ory/dockertest"
  version = "3.1.0"
```

to your Gopkg.toml and then run `dep ensure`. That should do the trick.

**Comment by calvn** [comment]
I'll try on a minimal repo that imports dockertest using dep, but can you try with version `3.3.0` since that's when you moved dockerclient?

**Comment by aeneasr** [comment]
Yeah sorry, I copied the wrong version there. But 3.3.0 does work because I needed 3.3.0 in order to get the build going again - because once again docker broke something which in turn broke this library and in turn my builds.

**Comment by aeneasr** [comment]
Oh it actually shows the gopkg in the readme...haven't updated that in a while. The issue is that main branch is v3 and no longer master which might break `go get`...

**Comment by calvn** [comment]
I think I have a path forward here. Using govendor to target `github.com/ory/dockertest@v3` seems to work. This can be closed now, thanks for the quick reply!

**Comment by aeneasr** [comment]
Perfect! I’ll keep it open to remind myself to update the readme. If you want, feel free to PR the new instructions :)

**Comment by aeneasr** [comment]
See #125
