### ISSUE TITLE
Do not publish ports on Linux

### ISSUE THREAD

**Issue by dennwc** [ory/dockertest#127]
Currently `dockertest` publishes all ports for the host. It's the only way to make it work for Windows, but on Linux there is no need to publish any ports since container can be accessed via Docker network (ex: `172.17.0.2`).

I propose to detect if the host OS is Linux, disable ports publishing and change the host address that is returned (see https://github.com/ory/dockertest/pull/126).

It might also fix the problem with https://github.com/ory/dockertest/issues/94.

**Comment by aeneasr** [comment]
This is solved

**Comment by dennwc** [comment]
I'm not sure it is. #126 only adds a method to retrieve a `host:port` pair, but the library still publishes all ports and returns a mapped `host:port` pair (`localhost:31234` instead of `172.17.0.2:3306`).

**Comment by aeneasr** [comment]
Oh, whoops :)

**Comment by aeneasr** [comment]
Hm, not publishing those ports would break older versions - how about a flag that tells dockertest explicitly to not publish the ports if on linux?

**Comment by dennwc** [comment]
You mean a global or a flag in `RunOptions`? Either way, it will solve the compatibility issue.

**Comment by aeneasr** [comment]
I think a global config (maybe at pool creation?) makes the most sense

**Comment by dennwc** [comment]
Sounds good! I'll work on it when I get some time.

**Comment by aeneasr** [comment]
Awesome!

**Comment by aeneasr** [comment]
I am closing this issue as it has not received any engagement from the community or maintainers in a long time. That does not imply that the issue has no merit. If you feel strongly about this issue

- open a PR referencing and resolving the issue;
- leave a comment on it and discuss ideas how you could contribute towards resolving it;
- open a new issue with updated details and a plan on resolving the issue.

We are cleaning up issues every now and then, primarily to keep the 4000+ issues in our backlog in check and to [prevent](https://www.jeffgeerling.com/blog/2020/saying-no-burnout-open-source-maintainer) [maintainer](https://www.jeffgeerling.com/blog/2016/why-i-close-prs-oss-project-maintainer-notes) [burnout](https://docs.brew.sh/Maintainers-Avoiding-Burnout). Burnout in open source maintainership is a [widespread](https://opensource.guide/best-practices/#its-okay-to-hit-pause) and serious issue. It can lead to severe personal and health issues as well as [enabling catastrophic](https://haacked.com/archive/2019/05/28/maintainer-burnout/) [attack vectors](https://www.gradiant.org/en/blog/open-source-maintainer-burnout-as-an-attack-surface/).

Thank you to anyone who participated in the issue! 🙏✌️

**Comment by davendu** [comment]
Well, if anyone else searched through the Internet like me, here is the solution:

```go
resource, err := pool.RunWithOptions(&dockertest.RunOptions{
	Repository: "foo", Tag: "bar",
}, func(m *dc.HostConfig) {
	m.PublishAllPorts = false
	m.Memory = 2 * consts.GB
})
ip := resource.Container.NetworkSettings.IPAddress
```

Should `PublishAllPorts` be exposed to `RunOptions`? Not sure.
