### ISSUE TITLE
Elasticsearch example

### ISSUE THREAD

**Issue by kshamko** [ory/dockertest#132]
I'm trying to build and run custom elasticsearch image with schema preinstalled
```
        pool, err := dockertest.NewPool("")
	if err != nil {
		log.Fatalf("Could not connect to docker: %s", err)
	}

	resource, err := pool.BuildAndRun("my-els", "../../elastic/image/Dockerfile", []string{})
	if err != nil {
		log.Fatalf("Could not start resource: %s", err)
	}

	if err := pool.Retry(func() error {
		var err error
		els, err = datasource.NewELS([]string{fmt.Sprintf("http://localhost:%s", resource.GetPort("9200/tcp"))})
		return err
	}); err != nil {
		log.Fatalf("Could not connect to docker: %s", err)
	}
```
But I have the following error  

> 2018/07/20 12:57:45 Could not connect to docker: health check timeout: Head http://localhost:32785: context deadline exceeded: no Elasticsearch node available

Container is being built and run but I'm not able to reach it from host machine. But once I start a container with **docker run** manually and define **--net** flag the issue is gone. So is it possible to define a network for the container started by dockertest. Thank you

**Comment by dennwc** [comment]
I had this problem as well and it might not be related to networking.

Check ElasticSearch log, it probably tells that kernel limits are too low.

Running this on the host might help:
```
sysctl -w vm.max_map_count=262144
```
Note: it won't persist after the reboot.

**Comment by kshamko** [comment]
Thanks for the response. I have this param set up in /etc/sysctl.conf . And i'm pretty confident that elastic is running

**Comment by aeneasr** [comment]
I am closing this issue as it has not received any engagement from the community or maintainers in a long time. That does not imply that the issue has no merit. If you feel strongly about this issue

- open a PR referencing and resolving the issue;
- leave a comment on it and discuss ideas how you could contribute towards resolving it;
- open a new issue with updated details and a plan on resolving the issue.

We are cleaning up issues every now and then, primarily to keep the 4000+ issues in our backlog in check and to [prevent](https://www.jeffgeerling.com/blog/2020/saying-no-burnout-open-source-maintainer) [maintainer](https://www.jeffgeerling.com/blog/2016/why-i-close-prs-oss-project-maintainer-notes) [burnout](https://docs.brew.sh/Maintainers-Avoiding-Burnout). Burnout in open source maintainership is a [widespread](https://opensource.guide/best-practices/#its-okay-to-hit-pause) and serious issue. It can lead to severe personal and health issues as well as [enabling catastrophic](https://haacked.com/archive/2019/05/28/maintainer-burnout/) [attack vectors](https://www.gradiant.org/en/blog/open-source-maintainer-burnout-as-an-attack-surface/).

Thank you to anyone who participated in the issue! 🙏✌️
