### ISSUE TITLE
Logging stdout from container for lambda

### ISSUE THREAD

**Issue by ptimson** [ory/dockertest#135]
I'm trying to use this to run my lambda function

```
options := &dockertest.RunOptions{
	Repository: "lambci/lambda",
	Tag:        "go1.x",
	Cmd:        []string{"lister", "{\"some\": \"event\"}"},
	Mounts: []string{"bin:/var/task"},
}

resource, err := pool.RunWithOptions(options)
if err != nil {
	log.Fatalf("Could not start resource: %s", err)
}
```

It is running but I'm not sure how to get the output / logs

**Comment by aeneasr** [comment]
I don't think there is an option, you'll have to use the CLI or something - or hack around with the original go-API :)

**Comment by pisarukv** [comment]
It's pretty simple. For my own purposes I have written a simple wrapper. https://gist.github.com/pisarukv/6e942d53a43f8973ce610af1398a2e68 Check [TailLogs](https://gist.github.com/pisarukv/6e942d53a43f8973ce610af1398a2e68#file-read-go-L37) method. I guess, it's what are you looking for.

**Comment by fraenky8** [comment]
@pisarukv links are dead, can you renew?

**Comment by aeneasr** [comment]
I am closing this issue as it has not received any engagement from the community or maintainers in a long time. That does not imply that the issue has no merit. If you feel strongly about this issue

- open a PR referencing and resolving the issue;
- leave a comment on it and discuss ideas how you could contribute towards resolving it;
- open a new issue with updated details and a plan on resolving the issue.

We are cleaning up issues every now and then, primarily to keep the 4000+ issues in our backlog in check and to [prevent](https://www.jeffgeerling.com/blog/2020/saying-no-burnout-open-source-maintainer) [maintainer](https://www.jeffgeerling.com/blog/2016/why-i-close-prs-oss-project-maintainer-notes) [burnout](https://docs.brew.sh/Maintainers-Avoiding-Burnout). Burnout in open source maintainership is a [widespread](https://opensource.guide/best-practices/#its-okay-to-hit-pause) and serious issue. It can lead to severe personal and health issues as well as [enabling catastrophic](https://haacked.com/archive/2019/05/28/maintainer-burnout/) [attack vectors](https://www.gradiant.org/en/blog/open-source-maintainer-burnout-as-an-attack-surface/).

Thank you to anyone who participated in the issue! 🙏✌️

**Comment by srenatus** [comment]
ℹ️ Just for the next person to stumble upon this: to read the output stream, you'll need to demux it via https://pkg.go.dev/github.com/docker/docker/pkg/stdcopy.
