### ISSUE TITLE
Absolute host path for mounts on Windows

### ISSUE THREAD

**Issue by npepinpe** [ory/dockertest#142]
**Describe the bug**

When trying to mount a host volume to a container using `RunWithOptions`, I run into either this problem:

> "../log" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path

If I do set an absolute path, however, on Windows this includes the drive, e.g. `C:`, so the parsing of the mount fails:

> invalid mount format: got C:\work\repo\db\migrations:/flyway/sql, expected <src>:<dst>

**To Reproduce**

Try executing:

```go
// for relative path
pool, _ := dockertest.NewPool("")
res, _ := pool.RunWithOptions(&dockertest.RunOptions{Repository: "postgres", Tag: "latest", Mounts: []string{"../../db:/data"})

// for absolute
pool, _ := dockertest.NewPool("")
res, _ := pool.RunWithOptions(&dockertest.RunOptions{Repository: "postgres", Tag: "latest", Mounts: []string{"C:\something\db:/data"})
```

**Expected behavior**
Using absolute path should work on all platforms.

**Version:**
 - Environment: Windows 10
 - Docker version: 18.06.1-ce-win73

**Comment by aeneasr** [comment]
Maybe try `C:/work/repo/db/migrations` or `C:\\work\\repo\\db\\migrations`

**Comment by MaikuMori** [comment]
@aeneasr Can we get this fixed? There are 2 fixes provided.
