### ISSUE TITLE
Run in Google Cloud Build

### ISSUE THREAD

**Issue by facundomedica** [ory/dockertest#145]
I've been using dockertest for quite a while, and now I started using Google Cloud Build. The problem is that I couldn't find a way of running dockertest in Cloud Build.

**Describe the solution you'd like**
I would like to have an example just like the Travis CI example in the readme.

**Describe alternatives you've considered**
I've tried installing docker within a docker container with no luck

**Comment by aeneasr** [comment]
Sorry, I can't help with that. Feel free to contribute a guide if you find out how to do it though.

**Comment by aeneasr** [comment]
Closing due to lack of interest

**Comment by ianlewis** [comment]
I'm not sure exactly what the issue the OP had was but for those who end up here, you can get it to work by attaching to the "cloudbuild" network and connecting to the IP address of the container rather than localhost.

```golang
list, _ := pool.NetworksByName("cloudbuild")
r, _ := pool.RunWithOptions(&dockertest.RunOptions{
    Networks: []*dockertest.Network{&list[0]},
})
```

And instead of `r.GetPort()`
```golang
func getPort(r *dockertest.Resource, port string) {
    n := r.Container.NetworkSettings.Networks["cloudbuild"]
    return net.JoinHostPort(n.IPAddress, port)
}
```

**Comment by nfiacco** [comment]
@ianlewis Looks like some of those functions no longer exist-- is there an updated approach I should use?

**Comment by ianlewis** [comment]
@nfiacco I think they should still exist. Which are you having a problem with?
1. `RunWithOptions`: https://github.com/ory/dockertest/blob/v3/dockertest.go#L362
2. `NetworksByName`: https://github.com/ory/dockertest/blob/v3/dockertest.go#L612

**Comment by nfiacco** [comment]
@ianlewis Ah looks like I was on an older version of dockertest, not a newer one. Also found that this worked for me as well:
```
r, _ := pool.RunWithOptions(&dockertest.RunOptions{...}, func(config *docker.HostConfig) {
	config.NetworkMode = "cloudbuild"
})
```

Still had to use the IP address of the container, and the port of the container (not the bound port of the host). So `5432` since I was connecting to a Postgres instance.

**Comment by ianlewis** [comment]
> @ianlewis Ah looks like I was on an older version of dockertest, not a newer one. Also found that this worked for me as well:
> 
> ```
> r, _ := pool.RunWithOptions(&dockertest.RunOptions{...}, func(config *docker.HostConfig) {
> 	config.NetworkMode = "cloudbuild"
> })
> ```

Ah, ok. I didn't realize you could set `NetworkMode` to the network name rather than setting `Network`. That makes it a bit simpler.
