### ISSUE TITLE
tmpfs mounts

### ISSUE THREAD

**Issue by marben** [ory/dockertest#150]
i may be missing something, but there don't seem to be a way to specify a tmpfs mounts.

**Is your feature request related to a problem? Please describe.**
I'd like to run my integration tests as fast as possible 

**Describe the solution you'd like**
I'd like to be able to specify tmpfs driver in mounts

**Comment by aeneasr** [comment]
Feel free to PR!

**Comment by osery** [comment]
Fyi there seems to be a way to do this using `RunWithOptions` and its `hcOpts` parameter as follows:
```go
resource, err := pool.RunWithOptions(&dockertest.RunOptions{
		Repository: image,
	}, func(config *docker.HostConfig) {
		config.Tmpfs = map[string]string{"/path/to/volume": "tmpfs options or empty"}
	})
```
Just tried 👍.

**Comment by aeneasr** [comment]
Closing as there seems to be a workaround

**Comment by JordanP** [comment]
It's 2023 and that workaround still works.
