### ISSUE TITLE
Provide API to remove old containers

### ISSUE THREAD

**Issue by zeeke** [ory/dockertest#151]
**Is your feature request related to a problem? Please describe.**
When I use the library in an integration test, some containers may survive test executions and I get errors because of multiple container with same name.

**Describe the solution you'd like**
Provide an API `RemoveContainerIfAny(name string)` that can be called at the very start of every test to be sure container list is clean.

**Describe alternatives you've considered**
Alternatively, I can implement the same function in my tests.

**Additional context**
This feature become important when managing "big" docker containers, like Oracle instances, as they can't be spawned like "normal", "small" containers.

(I can gladly provide a PR)

**Comment by aeneasr** [comment]
Yes, feel free to PR :)
