### ISSUE TITLE
GetBoundIP/GetHostPort do not reliably return remote IP of container 

### ISSUE THREAD

**Issue by nathanhruby** [ory/dockertest#153]
**Describe the bug**
When running against a remote docker engine, `GetBoundIP()` and `GetHostPort()` will most often return 0.0.0.0 or localhost unless the container has been specifically hardcoded to bind to a specific IP at create time.  In the default case,  ports are mapped to 0.0.0.0 to bind to all available IP's so extra logic needs to be run to determine the correct IP.

This type of run is the default for CircleCI where the provide access to a remote docker that may or may not be localhost.

**To Reproduce**
1. Fire up a docker machine on another host and get a machine env
2. Create a NewPool()
3. Create a resource
4. use `r. GetHostPort("the_port")` and dump the value

You can check out https://github.com/nathanhruby/test-dockertest for an example.

**Expected behavior**
`GetHostPort()` returns the remote IP of the container from `r.Container.NetworkSettings.Networks.bridge.IPAddress`

**Version:**
 - Environment: CircleCI
 - Version: 3.3.4

**Additional context**
Just checking the IPAddress value may be problematic on Docker For Mac since it's already running in a separate VM.  Probably the best case is to check for `DOCKER_HOST` env var being set and if so, using the container provided IP (which I assume may be different from the one in `DOCKER_HOST`) otherwise continue the current same behavior of assuming localhost.

**Comment by aeneasr** [comment]
Do you have an idea how to fix that behavior?

**Comment by nathanhruby** [comment]
Hey sorry for the late response.  Probably the easiest thing to do is check for `DOCKER_HOST` env var and if so use the container provided ip from `r.Container.NetworkSettings.Networks.bridge.IPAddress` otherwise, continue operating as is it does today.

**Comment by aeneasr** [comment]
I am closing this issue as it has not received any engagement from the community or maintainers in a long time. That does not imply that the issue has no merit. If you feel strongly about this issue

- open a PR referencing and resolving the issue;
- leave a comment on it and discuss ideas how you could contribute towards resolving it;
- open a new issue with updated details and a plan on resolving the issue.

We are cleaning up issues every now and then, primarily to keep the 4000+ issues in our backlog in check and to [prevent](https://www.jeffgeerling.com/blog/2020/saying-no-burnout-open-source-maintainer) [maintainer](https://www.jeffgeerling.com/blog/2016/why-i-close-prs-oss-project-maintainer-notes) [burnout](https://docs.brew.sh/Maintainers-Avoiding-Burnout). Burnout in open source maintainership is a [widespread](https://opensource.guide/best-practices/#its-okay-to-hit-pause) and serious issue. It can lead to severe personal and health issues as well as [enabling catastrophic](https://haacked.com/archive/2019/05/28/maintainer-burnout/) [attack vectors](https://www.gradiant.org/en/blog/open-source-maintainer-burnout-as-an-attack-surface/).

Thank you to anyone who participated in the issue! 🙏✌️

**Comment by reddec** [comment]
To whom it may concern: I was able to solve it by the following code

```go

func getHostPort(resource *dockertest.Resource, id string) string {
	dockerURL := os.Getenv("DOCKER_HOST")
	if dockerURL == "" {
		return resource.GetHostPort(id)
	}
	u, err := url.Parse(dockerURL)
	if err != nil {
		panic(err)
	}
	return u.Hostname() + ":" + resource.GetPort(id)
}
```

**Comment by aeneasr** [comment]
Awesome, thank you for sharing it with the community! If you’d like please open a PR in the README or for the GoDoc :)

**Comment by reddec** [comment]
@aeneasr https://github.com/ory/dockertest/pull/293
