### ISSUE TITLE
Remove Travis-CI set-up description

### ISSUE THREAD

**Issue by sekky0905** [ory/dockertest#154]
**Is your feature request related to a problem? Please describe.**
According to the following posts, Travis-CI had  two Linux infrastructures which are containers and virtual machines, but recently Travis-CI was combined two Linux infrastructures into a virtual machine-based Linux infrastructures.

https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration
https://blog.travis-ci.com/2018-10-04-combining-linux-infrastructures

So, we do not need add the following settings at travis.yml.

```yml
# Sudo is required for docker
sudo: required

# Enable docker
services:
  - docker
```

Actually I removed above settings from my travis.yml, but my tests passed Travis-CI checks.

**Describe the solution you'd like**
I'd like to remove the section of `Setting up Travis-CI` from [README.md](https://github.com/ory/dockertest/blob/v3/README.md)

**Comment by aeneasr** [comment]
Thank you and feel free to PR!

**Comment by sekky0905** [comment]
Thank you!
I'll do PR
