### ISSUE TITLE
add go mod command to README

### ISSUE THREAD

**Issue by cadethacker** [ory/dockertest#156]
**Describe the bug**
Add the go mod instructions to the README

**Additional context**
I am very new to golang, so I don't have the history in my head of module vs what is before it (dependencies?), but I know that when I tried to install using the `dep` command in the README, I had to switch to `go get -u github.com/ory/dockertest`.  Would it be ok to add that to the README with a comment like: 

```
If using go modules use this command to fetch the dependency

go get -u github.com/ory/dockertest
```

**Comment by aeneasr** [comment]
Feel free to PR!

**Comment by soniah** [comment]
Use this @cadethacker:

```
module dockertest_hack                                                           
                                                                                 
go 1.12.6                                                                        
                                                                                 
require (            
  ...                                                            
  github.com/ory/dockertest v3.3.4+incompatible                                  
  ...
)
```

Then `go mod download` or `go build` will download your dependencies.

**Comment by aeneasr** [comment]
It's in the README
