### ISSUE TITLE
Cockroachdb example

### ISSUE THREAD

**Issue by Inconnu08** [ory/dockertest#162]
I know it uses the same `Postgres` protocol but when I try to test a function, the begin transaction fails with `EOF`. How do you setup for cockroachdb?

	pool, err := dockertest.NewPool("")
	if err != nil {
		log.Fatalf("Could not connect to docker: %s", err)
	}

	resource, err := pool.Run("postgres", "9.6", []string{"POSTGRES_PASSWORD=secret", "POSTGRES_DB=" + database})
	if err != nil {
		log.Fatalf("Could not start resource: %s", err)
	}
	resource.Expire(60)

	if err = pool.Retry(func() error {
		var err error
		db, err = sql.Open("pgx", fmt.Sprintf("postgresql://postgres:secret@localhost:%s/%s?sslmode=disable", resource.GetPort("5432/tcp"), database))
		if err != nil {
			return err
		}
		return db.Ping()
	}); err != nil {
		log.Fatalf("Could not connect to docker: %s", err)
	}

	// When done, kill and remove the container
	tearDown :=  func() {
		pool.Purge(resource)
	}

**Comment by aeneasr** [comment]
I don't understand your question, you're clearly using the postgres image in your example code?

**Comment by Inconnu08** [comment]
Because I tried using cockroachdb like this:

```
pool, err := dockertest.NewPool("")
if err != nil {
	log.Fatalf("Could not connect to docker: %s", err)
}

resource, err := pool.Run("cockroachdb/cockroach", "v19.1.2", []string{"POSTGRES_PASSWORD=secret", "POSTGRES_DB=" + database})
```



But I get:

`Could not connect to docker: strconv.ParseUint: parsing "": invalid syntax`

**Comment by aeneasr** [comment]
It says that you can not connect to docker, which is a different error.

**Comment by aeneasr** [comment]
Please include full code samples. Also you've just copy-pasted the environment variables. Maybe you could ask a peer to help you with this.

**Comment by Inconnu08** [comment]
Closing this off as I could work successfully with Postgres instead.
