### ISSUE TITLE
Add example using two or more communicating containers

### ISSUE THREAD

**Issue by KantarBruceAdams** [ory/dockertest#163]
**Is your feature request related to a problem? Please describe.**

I'm trying to get two containers to communicate with each other.
I can start up each container and connect to it from the command line using localhost and the bound IP but I'm not clear how to get two containers to talk to each other.
I think this would be the equivalent of "docker network connect" https://stackoverflow.com/questions/18460016/connect-from-one-docker-container-to-another

**Describe the solution you'd like**

An example demonstrating how this works would be useful.

**Describe alternatives you've considered**

At the moment I am wading through the code to work out how things might work as it is not clear from the limitation documentation available.

**Additional context**

I am creating integration tests for a application acting as a gateway. I want to run the application as one docker container and the servers it connect to as other containers.
I can start the containers but I'm not sure how to make them talk to each other.
To keep the tests isolated I don't really want them to communicate directly using the localhosts network ports (for example I pull a rabbitmq image which would normally be on host at 5672, it don't want to use 5672 but using 127.0.0.1:33217 or whatever docker allocates to the bridge network would be fine).

**Comment by aeneasr** [comment]
The intention of this library isn't really orchestrating multiple containers but setting up 3rd party services with e.g. a database. If you need more sophisticated orchestration it might be wiser to create a `Makefile` with a combination of `docker-compose up` and `go test`.

**Comment by KantarBruceAdams** [comment]
I think the model I'm looking for is more like test containers.
Here are two (hopefully) compelling use cases:

You have something that needs to communicate with two or more 3rd party services that themselves communicate. In my case I am implementing a http to amqp gateway to a server that communicates to with a database. The server and the database need to communicate with each other. My service communicates with the server using amqp which requires both to have access to a rabbitmq broker.

You wish to test a docker image you are producing as the installation package. I have unit tests, I have program tests which operate by running the program as built with "go build" and I'm now trying to add a third level which tests the installation package (which is a docker image) with the real services rather than mocks. So my test actually starts the program under test as one of the images and connects that to the 3rd party services.

Why not use docker compose? Because I need programmatic control. I would end up having to generate the .yml files for each test. dockertest already has or is very close to what I require functionally. I am just missing how to run the equivalent of "docker network connect". I think it is probably https://godoc.org/gopkg.in/ory-am/dockertest.v3/docker#Client.ConnectNetwork.
What is ConnectNetwork() for if it isn't for doing this kind of thing? 

The reason I suggested an example is added is because it might more succinctly demonstrate how to manage this more complex case. An orthogonal improvement would be to have much more thorough documentation. That is much more work however.

**Comment by KantarBruceAdams** [comment]
In fact it just works so long as you use the right IP address rather than localhost.
E.g.
amqpURL := fmt.Sprintf("amqp://guest:guest@%s:%s", GetOutboundIP(), rabbitmq.Resource.GetPort("5672/tcp"))

pool.Client.ConnectNetwork("bridge", docker.NetworkConnectionOptions{Container: "bridge"}) is the default behaviour. I think the netwrok functionality is only needed if you want to create an isolated private network (which is probably a good idea).

**Comment by aeneasr** [comment]
Closed by #188

**Comment by SabreenKaur** [comment]
I have a query which is similarly related to this and would like to find out if my use case can be achieved using dockertest. I am new to dockertest and would appreciate any guidance.

My setup is that there are three services (X, Y and Z) that can be started by docker compose, producing 3 containers; one for each service. The images for each service are built using my own written Dockerfile.

I would like to write integration tests for these services to check that they can communicate based on various configurations of each service. For example I would like to write an integration test which tests whether service X can submit a request to service Y, given a single configuration. Therefore it would only make sense for the test to be executed within the container  that is running service X, not outside the docker container environment. From doing lots of research I have only found use cases using dockertest with DBs and implicitly it is assumed that the integration tests are run outside of the container, however this does not work for my use case as we need to be inside service X to make use of it functionality and submit a request to service Y. Therefore I was wondering if it is possible to specify within which container, specific integration tests are executed?
