### ISSUE TITLE
GetBoundIP/GetHostPort return empty string for local network

### ISSUE THREAD

**Issue by KantarBruceAdams** [ory/dockertest#164]
**Describe the bug**

The functions GetBoundIP  (func (r *Resource) GetBoundIP(id string) string) and GetHostPort return an empty string for the IP address.
An empty string is not a valid IP address so this should be error.

This is similar to https://github.com/ory/dockertest/issues/153, possibly even a duplicate.

**To Reproduce**

       // create a network with Client.CreateNetwork()
       net, err := suite.pool.Client.CreateNetwork(docker.CreateNetworkOptions{
			Name: netid,
		})

Create a container using:

	runopts := dockertest.RunOptions{
		Repository:   repository,
		Tag:          tag,
		Env:          []string{},
		ExposedPorts: []string{portString},
		Cmd:          cmd,
		NetworkID:    net.ID,
	}

	resource, err := suite.pool.RunWithOptions(
		&runopts,
		func(hostConfig *docker.HostConfig) {
			hostConfig.LogConfig.Type = "json-file"
		},
	)

       resource.Container.GetBoundIP() returns the empty string.

**Expected behavior**

The correct IP address can be obtained using:

   resource.Container.NetworkSettings.Networks[network.ID].IPAddress

I was expecting resource.Container.NetworkSettings.IPAddress to hold the same value.
That it doesn't also explains why GetBoundIP() fails.

It could be that I am missing some required setting in run options or run with options but it is not obvious what.

**Environment**

* Version: v3.4.4
* Environment: Debian9.3, Docker 18.09

**Additional context**

**Comment by aeneasr** [comment]
Thank you! Do you have an idea how to fix this? If so, feel free to fire up a PR!

**Comment by aeneasr** [comment]
I am closing this issue as it has not received any engagement from the community or maintainers in a long time. That does not imply that the issue has no merit. If you feel strongly about this issue

- open a PR referencing and resolving the issue;
- leave a comment on it and discuss ideas how you could contribute towards resolving it;
- open a new issue with updated details and a plan on resolving the issue.

We are cleaning up issues every now and then, primarily to keep the 4000+ issues in our backlog in check and to [prevent](https://www.jeffgeerling.com/blog/2020/saying-no-burnout-open-source-maintainer) [maintainer](https://www.jeffgeerling.com/blog/2016/why-i-close-prs-oss-project-maintainer-notes) [burnout](https://docs.brew.sh/Maintainers-Avoiding-Burnout). Burnout in open source maintainership is a [widespread](https://opensource.guide/best-practices/#its-okay-to-hit-pause) and serious issue. It can lead to severe personal and health issues as well as [enabling catastrophic](https://haacked.com/archive/2019/05/28/maintainer-burnout/) [attack vectors](https://www.gradiant.org/en/blog/open-source-maintainer-burnout-as-an-attack-surface/).

Thank you to anyone who participated in the issue! 🙏✌️
