### ISSUE TITLE
incompatible version with Go Modules (Go 1.13+)

### ISSUE THREAD

**Issue by adamdecaf** [ory/dockertest#173]
**Describe the bug**

When upgrading an application that uses dockertest Go 1.13's additional errors cause a build failure like: 

```
github.com/cenkalti/backoff@v2.2.0+incompatible: invalid version: +incompatible suffix not allowed: module contains a go.mod file, so semantic import versioning is required
```

- [build link](https://travis-ci.com/moov-io/paygate/jobs/232010308)

**To Reproduce**

I have the following in my `go.mod` file: 

```
github.com/ory/dockertest v3.3.4+incompatible
```

**Expected behavior**

Upgrade to a `/v3` import path and have `go build` complete without errors. 

**Environment**

* Go version: 1.13

**Additional context**

- [PR](https://github.com/moov-io/paygate/pull/246) / [Branch](https://github.com/adamdecaf/paygate/tree/go1.13)

**Comment by aeneasr** [comment]
Hi! Thank you for your contribution - just catching up to everything after a vacation :) Would you be up for a PR?
