### ISSUE TITLE
Support podman varlink interface

### ISSUE THREAD

**Issue by johanbrandhorst** [ory/dockertest#175]
**Is your feature request related to a problem? Please describe.**
The docker daemon famously runs as root and anyone with access to the docker daemon effectively has root on the machine. One of the docker alternatives that exists now is Podman, https://podman.io/, which offers a complete docker CLI replacement. Unfortunately, it does _not_ also provide a docker-daemon replacement on /var/run/docker.sock. Instead, it offers a `varlink` programmable interface (https://podman.io/blogs/2019/01/16/podman-varlink.html).

**Describe the solution you'd like**
Ideally we should be able to implement the subset of the Docker API required with a varlink backend.

**Describe alternatives you've considered**
...just using docker is an alternative. I'd like to avoid this though since it compromises security.

**Comment by johanbrandhorst** [comment]
Alternatively, as described in https://developers.redhat.com/blog/2019/02/21/podman-and-buildah-for-docker-users/, if we could implement a `runc` interface, that would be even better.

**Comment by johanbrandhorst** [comment]
Actually, I think we want to support `containerd`, which seems to delegate to `runc`, which talks to the kernel. I think. https://github.com/containerd/containerd.

**Comment by johanbrandhorst** [comment]
Nope, podman doesn't seem to be using containerd. Seems we'd need to talk to runc directly or the varlink interface.

**Comment by johanbrandhorst** [comment]
Here's the API spec: https://github.com/containers/libpod/blob/master/API.md. There's a few examples of using it from Go, but there doesn't seem to be an official Go client.

**Comment by johanbrandhorst** [comment]
Ooh, there IS a go interface, but it's generated from an IDL. The official spec for the interface is here: https://github.com/containers/libpod/blob/master/cmd/podman/varlink/io.podman.varlink and the go generator is here: https://github.com/varlink/go/.

**Comment by aeneasr** [comment]
Sorry, this goes beyond the scope of this library.

**Comment by johanbrandhorst** [comment]
OK, thanks for your prompt response!
