### ISSUE TITLE
Build error in filesys_windows.go

### ISSUE THREAD

**Issue by jackwhelpton** [ory/dockertest#176]
**Describe the bug**

A recent change in the windows package has broken dockertest:

https://github.com/golang/sys/commit/5c00192e8ce6429d705e1e4d83b4b22e79482964#diff-c4ffa695b270239c949ef5b31be6c4f5

**To Reproduce**

Attempts to build tests that use the dockertest package fail with:

```
github.com\ory\dockertest@v3.3.5+incompatible\docker\pkg\system\filesys_windows.go:113:24: cannot use uintptr(unsafe.Pointer(&sd[0])) (type uintptr) as type *"golang.org/x/sys/windows".SECURITY_DESCRIPTOR in assignment
```

**Expected behavior**

Tests build successfully.

**Environment**

* Windows Version: 10 (Version 1903)
* Go Version: 1.13

**Additional context**

**Comment by jackwhelpton** [comment]
This also seems related: https://github.com/fsouza/go-dockerclient/commit/348231a36c194e55957e123fbd6f5909916e4f51

**Comment by jackwhelpton** [comment]
As a temporary workaround, adding this to the .mod file of the project under test works:
```
replace golang.org/x/sys => golang.org/x/sys v0.0.0-20190813064441-fde4db37ae7a
```

**Comment by aeneasr** [comment]
Would you be open for a PR to fix this with the mentioned workaround?

**Comment by jackwhelpton** [comment]
I'd forked ready to create a PR, but wasn't sure of the exact approach to take. I don't have much familiarity with `dep`; by the time versioning became a real pain point for us I took the leap to vgo/modules and haven't looked back.

The fix referred to above is not part of the dockertest project itself, but a line I add to the module file for my application that _uses_ dockertest. If I run `go mod why -m golang.org/x/sys`, it is GCP packages and not dockertest that are resulting in this dependency. I'm not sure why it's not being version-locked by Gopkg.lock, perhaps some interplay (or lack thereof) between `go mod` and `dep`?

Long waffle cut short, I think I saw a ticket for migrating dockertest to modules and this'll probably be easier to fix once that has been done. Even then, I suspect we should change the way we interact with `golang/x/sys` to match the new code rather than pinning ourselves to an older version.

Any thoughts?

**Comment by jackwhelpton** [comment]
Looking back at that modules ticket I can't see a commitment to produce a PR, so I've raised one of my own to take that first step. I've validated that tests still pass locally, although consumers of the library via modules will need to add a /v3 to their import paths.

https://github.com/ory/dockertest/pull/177

**Comment by aeneasr** [comment]
Yes absolutely, let's move to go modules!

**Comment by jackwhelpton** [comment]
I think I need to expand the module change so that the sub-packages reference the versioned parent... PR coming up once I've verified that change locally.

**Comment by jackwhelpton** [comment]
I think we'll want to merge this change next, feedback welcome:

https://github.com/ory/dockertest/pull/178

I only came across this when using types from sub-packages.

**Comment by jackwhelpton** [comment]
I've raised a second PR, which builds on the modules work and addressing the underlying problem so that we can use the newer versions of dependencies.

https://github.com/ory/dockertest/pull/179

Note that this incorporates 178, so if we're happy with this we can merge 179 and just close 178.
