### ISSUE TITLE
running dockertest in gitlabCI?

### ISSUE THREAD

**Issue by bart6114** [ory/dockertest#181]
I can't get my tests to run in GitlabCI (no issues when running locally). Could someone point me to an example `gitlab-ci.yml` we're they are able to pull this off?

I keep running in to this error: `dial tcp [::1]:32769: connect: connection refused`

**Comment by bart6114** [comment]
nevermind, got this fixed. trying to point to the wrong host, localhost instead of the docker daemon...

**Comment by chrisbbe** [comment]
Maybe you could share your `gitlab-ci.yml` file to help other people? :)

**Comment by tacurran** [comment]
@Bart6114  please open a pr and we can include the .yml

**Comment by northrup** [comment]
@Bart6114 could you share your `gitlab-ci.yml`?

**Comment by tacurran** [comment]
@northrup we never heard back from @Bart6114 . You might also try community.ory.sh or the Discord Channel since many people in the Ory community use GitLab.

**Comment by bart6114** [comment]
Apologies for ignoring this ;) 

We moved away from `dockertest` in the end as it wasn't a scalable solution for our usecase.

If I remember correctly, when testing locally with `dockertest` it was possible to connect to the created docker container by pointing to `localhost:YOUR_CONTAINER_PORT`. However, when on a Gitlab shared runner your docker-machine is connected as a service. By default you would have to access this via `docker:YOUR_CONTAINER_PORT`. Note that this behaviour can change based on the type of gitlab-runner you're using.
