### ISSUE TITLE
Dependency seems to be broken

### ISSUE THREAD

**Issue by prochac** [ory/dockertest#182]
I get panic if i use `(*Pool).Retry(op func() error) error` function

I have reported it to causing library:
https://github.com/cenkalti/backoff/issues/87

**Comment by aeneasr** [comment]
Please use go modules

**Comment by prochac** [comment]
True, I have accidentally upgraded damaged package to higher version. github.com/cenkalti/backoff/v3@v3.2.1 instead of v3.0.0
