### ISSUE TITLE
security email not found 

### ISSUE THREAD

**Issue by adamdecaf** [ory/dockertest#185]
**Describe the bug**

I tried emailing `security@ory.sh` from [the linked security policy](https://github.com/ory/dockertest/security/policy), but got back an error email about that mailbox not existing. 

**To Reproduce**

Email `security@ory.sh`. 

<img width="1089" alt="Screen Shot 2020-01-21 at 10 42 33 AM" src="https://user-images.githubusercontent.com/120951/72833013-c4751a80-3c3a-11ea-8e33-ccfd7b53070f.png">

**Comment by adamdecaf** [comment]
cc @aeneasr

**Comment by aeneasr** [comment]
Oh, sorry about that - I've fixed the alias. We had a correct alias for our old domain security@ory.am and recently updated the security templates to update that to security@ory.sh without checking if that forward actually works. This is now resolved an you can send emails to security@ory.sh! Thank you for lettings us know :)

**Comment by adamdecaf** [comment]
Thanks. I noticed the [contributing guide](https://github.com/ory/dockertest/blob/v3/CONTRIBUTING.md#disclosing-vulnerabilities) mentions `hi@` instead of `security@`.
