### ISSUE TITLE
Dockertest with 12.2+ does not work

### ISSUE THREAD

**Issue by renevall** [ory/dockertest#190]
**Describe the bug**

Trying to use Dockertest with postgres 12.2+ throws connection refused. 

>2020/02/14 22:10:19 ping err:dial tcp [::1]:32768: connect: connection refused
2020/02/14 22:10:24 ping err:dial tcp [::1]:32768: connect: connection refused
2020/02/14 22:10:29 ping err:dial tcp [::1]:32768: connect: connection refused
2020/02/14 22:10:34 ping err:dial tcp [::1]:32768: connect: connection refused
2020/02/14 22:10:39 ping err:dial tcp [::1]:32768: connect: connection refused
2020/02/14 22:10:44 ping err:dial tcp [::1]:32768: connect: connection refused
2020/02/14 22:10:49 ping err:dial tcp [::1]:32768: connect: connection refused
2020/02/14 22:10:54 ping err:dial tcp [::1]:32768: connect: connection refused

**To Reproduce**

Follow samples and use:
`c, err := NewContainer("", "postgres", "latest", []string{"--rm"})`

**Expected behavior**

We should be able to connect and run tests normally. The last one that seems to work is 12.1

**Environment**

* Environment: Bitbucket with go-1.13-alpine

**Additional context**

I was using latest as tag for the postgres container. Today out of nowhere the pipeline started to fail. I tracked down to the 12.2 release that happened today if you check postgres' docker.

**Comment by aeneasr** [comment]
Pretty sure that has nothing to do with dockertest but instead something with postgres. I would start by checking the postgres docker container logs.

**Comment by renevall** [comment]
@aeneasr I agree. I'll leave it as reference that 12.1 works just fine if anyone comes looking.
