### ISSUE TITLE
Getting dial tcp [::1]:32768: connect: connection refused from gitlab ci

### ISSUE THREAD

**Issue by glossd** [ory/dockertest#191]
Locally it's all working, but when I run it in gitlab ci I get this error `dial tcp [::1]:32768: connect: connection refused`

In CI I configured `DOCKER_HOST` variable pointing to `tcp://docker:2375`

` dockertest.NewPool("") ` should connect to docker daemon.

**Comment by aeneasr** [comment]
Which version of dockertest are you using? Are you sure `tcp://docker:2375` is the URL where docker is running? You can confirm that by SSHing into the CI container.

**Comment by glossd** [comment]
`dockertest` version is v3.3.5 . I can assure you docker daemon is available on that url. I've run tests with java testcontainers library and everything was all right. But golang testcontainers showed the same error(((

**Comment by aeneasr** [comment]
That sounds like a misconfiguration then, CircleCI and TravisCI work fine. I don't think I can help you here.

**Comment by carlows** [comment]
@aeneasr I'm getting this same error but looks to be raised when trying to connect to the container.

I'm trying a simple setup with docker and postgres:

```
docker build -t container .
docker network create --driver bridge test_network
docker run --network=test_network container go test ./...

results in: dial tcp: lookup docker on 127.0.0.11:53: no such host
```

The code:

```
pool, _ := dockertest.NewPool("")

resource, _ := pool.Run("postgres", "13-alpine", []string{"POSTGRES_PASSWORD=secret", "POSTGRES_DB=" + databaseName})

pgURL := fmt.Sprintf("postgres://postgres:secret@localhost:%s/%s?sslmode=disable", resource.GetPort("5432/tcp"), databaseName)

err = pool.Retry(func() error {
        var err error
        db, err = gorm.Open("postgres", pgURL)
	if err != nil {
		return err
	}
	return db.DB().Ping()
})
```

What is missing for this to work?

**Comment by aeneasr** [comment]
I don't use GitLab so I don't know, sorry!

**Comment by carlows** [comment]
@aeneasr what I mentioned was not related to GitLab 😛 it is just a docker image I'm running locally.

**Comment by aeneasr** [comment]
This issue is about GitLab, if you have another problem please use a separate issue, thank you!

**Comment by glossd** [comment]
It took some time to figure it out)
In the examples the `pool.Retry` tries to connect to `localhost` whereas gitlab service runs `docker:dind` image (with container name `docker`) along side with the golang container where all the scripts get executed. 
The database container runs inside that `docker:dind` container which means if I wish to connect to db container  I should specify `docker` as a db host, not `localhost`

**Comment by glossd** [comment]
### Example `gitlab-ci.yml` 

```yaml
go-test:
  stage: test
  image: golang:1.15
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    DB_HOST_OF_YOUR_APP: docker
  script:
    - go test ./...
```
* You need to have `DB_HOST_OF_YOUR_APP` environment variable setting your database host.

**Comment by aeneasr** [comment]
Could you maybe add this to the readme so others can find this information quickly? :)

**Comment by glossd** [comment]
@aeneasr In order to make it work in gitlab ci the retry database host in the examples should be `docker host`,  not localhost. Do you think it's worth to change the examples for the sake of gitlab ci or just put the note about it in readme?
Additionally the application's database host must be configurable through environment variables.
Should I add this note to the root readme?

**Comment by king-11** [comment]
Thanks @glossd saved me quite some debugging
