### ISSUE TITLE
Panic when calling pool.Purge

### ISSUE THREAD

**Issue by jefferai** [ory/dockertest#192]
**Describe the bug**

When I call pool.Purge on my resource I get a panic from Go's HTTP lib. This is true for both dockertest 3.3.5 and 3.5.4, and with Go 1.13.8 and Go 1.14.

**To Reproduce**

Here's my exact code; when I call Purge I get a panic:
```go
func (b *BaseServer) CreateDevDatabase() error {
        pool, err := dockertest.NewPool("")
        if err != nil {
                return fmt.Errorf("could not connect to docker: %w", err)
        }

        resource, err := pool.Run("postgres", "latest", []string{"POSTGRES_PASSWORD=secret", "POSTGRES_DB=testdb"})
        if err != nil {
                return fmt.Errorf("could not start resource: %w", err)
        }

        if err := pool.Retry(func() error {
                db, err := sql.Open("postgres", fmt.Sprintf("postgres://postgres:secret@localhost:%s/testdb?sslmode=disable", resource.GetPort("5432/tcp")))
                if err != nil {
                        return fmt.Errorf("error opening postgres dev container: %w", err)
                }
                var mErr *multierror.Error
                if err := db.Ping(); err != nil {
                        mErr = multierror.Append(fmt.Errorf("error pinging dev database container: %w", err))
                }
                if err := db.Close(); err != nil {
                        mErr = multierror.Append(fmt.Errorf("error closing dev database container: %w", err))
                }
                return mErr.ErrorOrNil()
        }); err != nil {
                return fmt.Errorf("could not connect to docker: %w", err)
        }

        b.dockertestPool = pool
        b.dockertestResource = resource

        return nil
}

func (b *BaseServer) DestroyDevDatabase() error {
        if b.dockertestPool == nil {
                return nil
        }

        if b.dockertestResource == nil {
                return errors.New("found a pool for dev database container but no resource")
        }

        /*
                if err := b.dockertestResource.Expire(1); err != nil {
                        // Attempt purge anyways
                        b.dockertestPool.Purge(b.dockertestResource)
                        return fmt.Errorf("error setting expiry on the dev database container (attempted purge anyways): %w", err)
                }
        */

        return b.dockertestPool.Purge(b.dockertestResource)
}
```
I get the following panic (lines valid for Go 1.14):
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x7d5102]

goroutine 57 [running]:
net/http.(*conn).serve(0xc000266460, 0x145aee0, 0xc0001c2870)
        /home/jeff/src/go/src/net/http/server.go:1766 +0x42
created by net/http.(*Server).Serve
        /home/jeff/src/go/src/net/http/server.go:2933 +0x35c
```
If I comment out the Purge I get no panic (but also the container remains).

**Expected behavior**

No panic! :-)

**Comment by jefferai** [comment]
Something maybe of interest: If I call create and destroy very quickly, instead of the panic, I get `No such container: b09b79305ff20f6695eb92afc3e8d57bb5447ed1189f32a34eaffb881d72e1f0`.

I guess this indicates that the resource is returned before the container is fully created -- but then wouldn't the `pool.Retry` not return, or return an error, since it requires opening a connection to the db successfully? If I wait several seconds though, presumably for the container to fully initialize, I get the panic.

**Comment by aeneasr** [comment]
The panic shows a panic in your server, not dockertest. Are you sure this is a dockertest issue?

> Something maybe of interest: If I call create and destroy very quickly

The operation is async so yeah this can happen but as the scope of dockertest is very narrow I don't think it's an issue.

**Comment by jefferai** [comment]
A simple test program with just those functions behaves normally. The thing is, although my program does instantiate an http.Server and listen, no actual connections are being made to it. It's panicking trying to handle a connection, but I can say with fairly good certainty that the thing making the connection is not my code. I can reliably make it go away by commenting out those two functions, and reliably bring it back by enabling them, but I will keep looking at my code.

I am still not understanding why I'd see the "no such container" error if I shut down rapidly given the `pool.Retry` call with no error coming from it.

**Comment by aeneasr** [comment]
Unless the panic trace points to dockertest, proof is lacking that dockertest is causing the panic, and I do not have anything I can work with to fix it. Instead, it appears to be an issue with the way you instantiate or free your HTTP server which could of course be linked to your use of dockertest, but which is not an issue in dockertest itself.

**Comment by jefferai** [comment]
Understood. Actively debugging now. Please give me a bit to try to figure out the root cause. I agree it's likely not dockertest, but would like to try to add it here for completeness' sake.

**Comment by jefferai** [comment]
Found it: https://github.com/golang/go/issues/37663

Apologies for the noise. Using dockertest caused timing to change enough to surface this panic before the program closed. I had originally thought that dockertest might be using a server internally. Thanks for being patient!
