### ISSUE TITLE
Perform an action on termination of a container

### ISSUE THREAD

**Issue by KantarBruceAdams** [ory/dockertest#193]
**Is your feature request related to a problem? Please describe.**

I have an integration test which sometimes fails due to an issue with a container running rabbitmq:3-management. Either the rabbitmq server crashes or the container is stopped somehow.

I would like to report the termination of the container and possibly run a command like docker cp containerid:/path/to/log/file.
I am already capturing stdout and stderr but these end abruptly and unexpectedly.

**Describe the solution you'd like**

A hook for a function to be called when a container terminates. Such as a destructor like function

**Describe alternatives you've considered**

Keeping the container around after its executed is possible but challenging when you have multiple tests and don't know which if any  are going to fail in advance.

The best I can do at present is try to perform an action when I detect the test has failed.

**Additional context**

Also I note that https://godoc.org/gopkg.in/ory-am/dockertest.v3#Resource when I click on dc.Container it links to https://godoc.org/github.com/ory/dockertest/v3/docker#Container which is a 404. 
It may be there is asome existing Docker API I've missed. It may also be that there is a bug in your godoc documentation.

**Comment by aeneasr** [comment]
I'm not sure if that's possible because we're not able to observe containers in Dockertest. But if you can figure out a way, I'd highly appreciate a PR.

Your links don't work because the first link is the old import `ory-am` :)

**Comment by KantarBruceAdams** [comment]
I'm new to both docker and go so that may be a tall order but you never know.

The link is still broken for  https://godoc.org/gopkg.in/ory/dockertest.v3#Resource

**Comment by KantarBruceAdams** [comment]
I have a thought as to how this might work. First identify the main process in the container using:

     docker inspect -f '{{.State.Pid}}' <container id>

As per https://stackoverflow.com/questions/34878808/finding-docker-container-processes-from-host-point-of-view
I'm not sure what the equivalent is from the docker and dockertest APIs.
Then attach to the process using ptrace().
As per for example https://stackoverflow.com/questions/11216422/monitor-a-process-everything
Presumably using https://godoc.org/github.com/tfogal/ptrace#Tracee

**Comment by aeneasr** [comment]
I am closing this issue as it has not received any engagement from the community or maintainers in a long time. That does not imply that the issue has no merit. If you feel strongly about this issue

- open a PR referencing and resolving the issue;
- leave a comment on it and discuss ideas how you could contribute towards resolving it;
- open a new issue with updated details and a plan on resolving the issue.

We are cleaning up issues every now and then, primarily to keep the 4000+ issues in our backlog in check and to [prevent](https://www.jeffgeerling.com/blog/2020/saying-no-burnout-open-source-maintainer) [maintainer](https://www.jeffgeerling.com/blog/2016/why-i-close-prs-oss-project-maintainer-notes) [burnout](https://docs.brew.sh/Maintainers-Avoiding-Burnout). Burnout in open source maintainership is a [widespread](https://opensource.guide/best-practices/#its-okay-to-hit-pause) and serious issue. It can lead to severe personal and health issues as well as [enabling catastrophic](https://haacked.com/archive/2019/05/28/maintainer-burnout/) [attack vectors](https://www.gradiant.org/en/blog/open-source-maintainer-burnout-as-an-attack-surface/).

Thank you to anyone who participated in the issue! 🙏✌️
