### ISSUE TITLE
major version must be compatible

### ISSUE THREAD

**Issue by elgohr** [ory/dockertest#196]
**Describe the bug**

Using go 1.14 with
```
go get -u github.com/ory/dockertest@v3.5.4
```
results in 
```
go get github.com/ory/dockertest@v3.5.4: github.com/ory/dockertest@v3.5.4: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v3
```

When running 
```
go get -u github.com/ory/dockertest
```
it takes
```
github.com/ory/dockertest v3.3.5+incompatible
```

**Expected behavior**

Using latest dockertest version in latest go version

**Comment by aeneasr** [comment]
```
go get -u github.com/ory/dockertest/v3
```

see [go modules](https://blog.golang.org/v2-go-modules)

**Comment by elgohr** [comment]
Could we add this here?
`github.com/ory/dockertest@v3.x.y` is confusing here
https://github.com/ory/dockertest/blob/v3/README.md#installing-and-using-dockertest

**Comment by aeneasr** [comment]
Sure! Would you be open to PR that? :)
