### ISSUE TITLE
 localhost:2375 as default pool no longer working on windows

### ISSUE THREAD

**Issue by kbudde** [ory/dockertest#202]
**To Reproduce**

Running the previously working code throws an error now:

    dockertest.NewPool("")
    (noerror)
    ...
    resource, err := pool.BuildAndRunWithOptions("./testenv/Dockerfile", &dockertest.RunOptions{Name: "test", Hostname: "localtest"})
	if err != nil {
		log.Fatalf("Could not start resource: %s", err)
	}

Error:
`Could not start resource: : Post http://localhost:2375/build?dockerfile=Dockerfile&t=rabbitmq-test: dial tcp [::1]:2375: connectex: No connection could be made because the target machine actively refused it. `

**Expected behavior**

default pool should use working default.

Initialising docker.NewPool("npipe:////./pipe/docker_engine") works.

**Environment**

- Version: github.com/ory/dockertest/v3 v3.6.0
- Environment: windows 1909

**Comment by aeneasr** [comment]
Oh I'm not sure how Windows Pipes would work with Dockertest, sorry. But PRs welcome! You probably need to bump the deps though, which is very painful with Dockertest 😓

**Comment by zfedoran** [comment]
@kbudde I'm also seeing this issue but got around it by using WSL2 on Windows with an ubuntu image and then running my tests from there. WSL2 will seamlessly work with the docker engine running on the Windows host machine, so while it is a bit annoying, it at least allowed me continue using dockertest. I hope that helps :)

edit: If anyone needs help getting this going, the following helped me out: https://www.youtube.com/watch?v=idW-an99TAM

**Comment by aeneasr** [comment]
Thank you! I will be closing this issue as there is a workaround :)

**Comment by pellared** [comment]
@aeneasr Can you reopen it? The workaround is not really working if you really want to test things on Windows? E.g. if your code under test is Windows dependent.
