### ISSUE TITLE
Cannot upgrade dependencies in MacOS (amd64,darwin)

### ISSUE THREAD

**Issue by amckinney** [ory/dockertest#208]
When I attempt to upgrade my Go module dependencies, I'm encountering the following error.

```
.../go/pkg/mod/github.com/ory/dockertest/v3@v3.6.0/docker/pkg/term/tc.go:13:28: undefined: unix.SYS_IOCTL
.../go/pkg/mod/github.com/ory/dockertest/v3@v3.6.0/docker/pkg/term/tc.go:18:28: undefined: unix.SYS_IOCTL
.../go/pkg/mod/github.com/ory/dockertest/v3@v3.6.0/docker/pkg/term/termios_bsd.go:24:31: undefined: unix.SYS_IOCTL
.../go/pkg/mod/github.com/ory/dockertest/v3@v3.6.0/docker/pkg/term/termios_bsd.go:37:31: undefined: unix.SYS_IOCTL
```

I was able to trace down the issue to the [recent commit](https://github.com/golang/sys/commit/6fcdbc0bbc04dcd9e7dc145879ceaf9bf1c6ff03) in `golang/org/x/sys`.

**To Reproduce**

From the root of my repository:

```
$ go mod init github.com/foo/bar
$ go mod edit -go=1.14
$ go get -u -t ./...
```

**Expected behavior**

The upgrade should complete successfully.

**Environment**

```
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
```

**Comment by johanbrandhorst** [comment]
Moby seems to have moved away from this package to a specific module: https://github.com/moby/moby/tree/master/pkg/term. It seems this might suffer from the same issue though: https://github.com/moby/term/blob/master/tc.go#L13

**Comment by aeneasr** [comment]
```
go get -u -t ./...
```

is always a very dangerous command but nevertheless this should not fail. I'll check if I can reproduce it - would be nicer of course if you have a reproducible repo :)

**Comment by phumberdroz** [comment]
This is the minimal example I could come up with:
https://github.com/phumberdroz/dockertest

```
go mod init github.com/phumberdroz/dockertest
go mod edit -go=1.14
go get github.com/ory/dockertest/v3
go get github.com/sirupsen/logrus
go get -u ./...
```

And this is also affecting us.

**Comment by phumberdroz** [comment]
And it is also affecting us. :(

**Comment by aeneasr** [comment]
For workaround see https://github.com/ory/dockertest/issues/212#issuecomment-685167115

**Comment by tklauser** [comment]
> Moby seems to have moved away from this package to a specific module: https://github.com/moby/moby/tree/master/pkg/term. It seems this might suffer from the same issue though: https://github.com/moby/term/blob/master/tc.go#L13

This should be addressed in `github.com/moby/term` by moby/term#16

**Comment by tyrannosaurus-becks** [comment]
I can confirm that the workaround provided by @sethvargo works. To elaborate, if I first add this line to my `go.mod` file that's on Go `1.14`:

```
replace golang.org/x/sys => golang.org/x/sys v0.0.0-20200826173525-f9321e4c35a6
```

And then execute:

```
go get -u github.com/ory/dockertest/v3
```
It's successful for me. Just sharing this so others can use it until a fix is available.

**Comment by alextanhongpin** [comment]
> I can confirm that the workaround provided by @sethvargo works. To elaborate, if I first add this line to my `go.mod` file that's on Go `1.14`:
> 
> ```
> replace golang.org/x/sys => golang.org/x/sys v0.0.0-20200826173525-f9321e4c35a6
> ```
> 
> And then execute:
> 
> ```
> go get -u github.com/ory/dockertest/v3
> ```
> 
> It's successful for me. Just sharing this so others can use it until a fix is available.

Hi, I'm facing the same problem. I followed the steps above, but I got this error:

```
../../../../pkg/mod/github.com/ory/dockertest/v3@v3.6.0/docker/pkg/term/tc.go:13:28: undefined: unix.SYS_IOCTL
../../../../pkg/mod/github.com/ory/dockertest/v3@v3.6.0/docker/pkg/term/tc.go:18:28: undefined: unix.SYS_IOCTL
../../../../pkg/mod/github.com/ory/dockertest/v3@v3.6.0/docker/pkg/term/termios_bsd.go:24:31: undefined: unix.SYS_IOCTL
../../../../pkg/mod/github.com/ory/dockertest/v3@v3.6.0/docker/pkg/term/termios_bsd.go:37:31: undefined: unix.SYS_IOCTL
```

**Comment by alextanhongpin** [comment]
^ My bad, the solution above works.

**Comment by dzrtc** [comment]
This looks relevant: https://github.com/golang/go/commit/d140c357442471ca0d56615811fb4226e99fadd5#diff-e7b682af1287fd85958d5a8fb38192f3

**Comment by johanbrandhorst** [comment]
https://github.com/ory/dockertest/issues/212#issuecomment-685162574 explains the proper fix.

**Comment by johanbrandhorst** [comment]
Is there a plan to make a new release with this fix?

**Comment by aeneasr** [comment]
Done, thanks for the poke
