### ISSUE TITLE
github.com/Nvveen/Gotty has disappeared 

### ISSUE THREAD

**Issue by adamdecaf** [ory/dockertest#211]
**Describe the bug**

The package [`github.com/Nvveen/Gotty`](https://github.com/Nvveen/Gotty) seems to have disappeared from GitHub. I'm not sure if @Nvveen has made it private or just deleted the code, but it's [failing builds now](https://github.com/moov-io/paygate/runs/1057921164?check_suite_focus=true#step:7:1246). 

pkg.go.dev: https://pkg.go.dev/github.com/Nvveen/Gotty?tab=doc 

**To Reproduce**

```
GOPROXY=direct go get -u github.com/Nvveen/Gotty 
```
Outputs: 
```
go get github.com/Nvveen/Gotty: module github.com/Nvveen/Gotty: git ls-remote -q origin in /Users/adam/code/pkg/mod/cache/vcs/6bea29632aef13c27b8c63bd69ba0ce119aaeb94af0de885c0fcea456849dca7: exit status 128:
	ERROR: Repository not found.
	fatal: Could not read from remote repository.
	
	Please make sure you have the correct access rights
	and the repository exists.
```

**Comment by adamdecaf** [comment]
Btw, this Gotty is specified in the `go.mod` - https://github.com/ory/dockertest/blob/v3/go.mod#L8

Can we just replace it? There are other terminal libraries available.

See: https://github.com/ory/dockertest/blob/fa707f0f1b6a47c655ff73724436a1cfc505137e/docker/pkg/jsonmessage/jsonmessage.go#L263

**Comment by adamdecaf** [comment]
I found a copy of the source code in my GOPATH, could upload it.

**Comment by Nvveen** [comment]
I'm sorry, I thought it was an unused package, hadn't updated it in 8 years. If you could adopt it or replace it, that would be great.

**Comment by phumberdroz** [comment]
Would you for now be able to restore it?

**Comment by phumberdroz** [comment]
this still seems to be working `GOPROXY=https://proxy.golang.org GO111MODULE=on go get github.com/Nvveen/Gotty`

**Comment by adamdecaf** [comment]
Using Go's proxy works, but tons of machines don't have that set.

**Comment by adamdecaf** [comment]
@Nvveen If you could restore the package I think that'd be the quickest option. dockertest should probably be on an updated package.

**Comment by Nvveen** [comment]
I did not have an old copy of the repository and it had been forked so I can't restore it via the interface, so I submitted a support ticket to have it restored by Github.

**Comment by adamdecaf** [comment]
Thanks. Here's a copy I have from my $GOPATH.

[gotty.tar.gz](https://github.com/ory/dockertest/files/5159182/gotty.tar.gz)

**Comment by Nvveen** [comment]
It has been restored. Sorry for the inconvenience.

**Comment by adamdecaf** [comment]
Many thanks!
