### ISSUE TITLE
No longer works on darwin

### ISSUE THREAD

**Issue by sethvargo** [ory/dockertest#212]
**Describe the bug**

```
../go/pkg/mod/github.com/ory/dockertest@v3.3.5+incompatible/docker/pkg/term/tc.go:13:28: undefined: unix.SYS_IOCTL
../go/pkg/mod/github.com/ory/dockertest@v3.3.5+incompatible/docker/pkg/term/tc.go:18:28: undefined: unix.SYS_IOCTL
../go/pkg/mod/github.com/ory/dockertest@v3.3.5+incompatible/docker/pkg/term/termios_bsd.go:24:31: undefined: unix.SYS_IOCTL
../go/pkg/mod/github.com/ory/dockertest@v3.3.5+incompatible/docker/pkg/term/termios_bsd.go:37:31: undefined: unix.SYS_IOCTL
```

**To Reproduce**

1. Use mac/darwin
1. `go get -u github.com/x/sys/... github.com/ory/dockertest/v3`
1. See failure

**Expected behavior**

Not failing to build

**Environment**

- Mac OSX, all versions

**Additional context**

https://github.com/golang/sys/commit/196b9ba8737a10c9253b04174f25881e562da5b8
https://github.com/golang/sys/commit/6fcdbc0bbc04dcd9e7dc145879ceaf9bf1c6ff03

**Comment by ianlancetaylor** [comment]
This code should ideally be using `unix.IoctlGetTermios` and `unix.IoctlSetTermios`.  Direct system calls are considered unsupported by the Darwin maintainers.

https://pkg.go.dev/golang.org/x/sys/unix?tab=doc#IoctlGetTermios
https://pkg.go.dev/golang.org/x/sys/unix?tab=doc#IoctlSetTermios

**Comment by sethvargo** [comment]
In the meantime, you can pin sys to f9321e4c3, but that's not a viable long-term solution:

```sh
go get golang.org/x/sys@f9321e4c35
```

**Comment by aeneasr** [comment]
Dupe #208

**Comment by xylo04** [comment]
It looks like in many cases, this is coming from `mksyscall.pl` which is bundled with golang, so the fix would need to start there. https://github.com/golang/go/issues/42241
