### ISSUE TITLE
Ability to set Config values when using RunWithOptions (to specify User/UID)

### ISSUE THREAD

**Issue by danielcooperxyz** [ory/dockertest#253]
**Is your feature request related to a problem? Please describe.**
It would be good to be able to specify a user when running a container. Similar to the `-u` parameter when using `docker run`

**Describe the solution you'd like**
Ability to set  `User` option in the `Config` struct, possibly by specifying `Config` values when calling the `RunWithOptions` method, or with a `User` field in `RunOptions`.

**Describe alternatives you've considered**
Have tried to use the `CreateContainer` method directly, but there is a lot of logic in the `RunWithOptions` method that is useful
Currently have a workaround (method signature below) which is a copy of the `RunWithOptions` method that enables us to set Config options similar to HostConfig options. However this requires a custom resource struct as suggested below and makes it harder to use dockertest functionality.

    func RunWithConfigAndOptions(d *dockertest.Pool, cfgOpts []func(*dc.Config), opts *dockertest.RunOptions, hcOpts ...func(*dc.HostConfig)) (*Res, error) 

**Additional context**
Applications running inside the container currently write to disc as the dockerfile user which may or may not be root. It is possible to specify a user inside the dockerfile, but that user may not always be the same on every system.

**Comment by aeneasr** [comment]
Give it a shot in a PR and we'll see which way makes most sense :)

**Comment by aeneasr** [comment]
Merged
