### ISSUE TITLE
dockertest with postgres does not work 

### ISSUE THREAD

**Issue by azime** [ory/dockertest#266]
Hello,
i am trying to use dockertest but i am having errors.

here is a sample code:

```go

import (
	"database/sql"
	"flag"
	"fmt"
	"os"
	"testing"
	"time"

	_ "github.com/lib/pq"
	"github.com/ory/dockertest/v3"
	log "github.com/sirupsen/logrus"
)

var dockerDB *sql.DB

func TestMain(m *testing.M) {
	flag.Parse() //required to get Short() from testing
	if testing.Short() {
		log.Warn("skipping test Docker in short mode.")
		os.Exit(m.Run())
	}
	pool, err := dockertest.NewPool("")
	if err != nil {
		log.Fatalf("Could not connect to docker: %s", err)
	}

	resource, err := pool.Run("postgres", "9.4", []string{"POSTGRESQL_PASSWORD=secret", "POSTGRES_USER=user_name", "POSTGRES_DB=dbname"})
	if err != nil {
		log.Fatalf("Could not start resource: %s", err)
	}
	// exponential backoff-retry, because the application in the container might not be ready to accept connections yet
	pool.MaxWait = 30 * time.Second
	if err = pool.Retry(func() error {
		var errr error
		dockerDB, errr = sql.Open("postgres", fmt.Sprintf("postgres://user_name:secret@localhost:%s/dbname?sslmode=disable", "5432"))
		if errr != nil {
			return errr
		}
		return dockerDB.Ping()
	}); err != nil {
		log.Fatalf("Could not connect to docker: %s", err)
	}
	//Run tests
	code := m.Run()

	// You can't defer this because os.Exit doesn't care for defer
	if err := pool.Purge(resource); err != nil {
		log.Fatalf("Could not purge resource: %s", err)
	}

	os.Exit(code)
}

func TestRealbob(t *testing.T) {
	// all tests
}
```

I have this error: 
![image](https://user-images.githubusercontent.com/4006603/117452418-074c2600-af44-11eb-92be-8bb6cb82ca1e.png)

can you tell me why not working? 

Env: 

- Ubuntu 20.0.4 
- go version go1.13.8 linux/amd64

**Comment by scharissis** [comment]
It works for me. It definitely works, but it was a pain to make happen.

Two things to watch out for:

1. TestMain is a pain to use. Panics and defers can break things.
2. Check your ports! I needed to do something like this to get the port the container was bound to: `resource.GetPort("5432/tcp")`

Good luck!

**Comment by azime** [comment]
Hello
thank you for the answer.
no I can't even change the port `resource.GetPort("5432/tcp")` .
I still have the same message.
![image](https://user-images.githubusercontent.com/4006603/117774922-41664200-b23a-11eb-8570-d2d3ffd12a96.png)
at this line, the container does not start:
```go
resource, err := pool.Run("postgres", "9.4", []string{"POSTGRESQL_PASSWORD=secret", "POSTGRES_USER=user_name", "POSTGRES_DB=dbname"})
```
`docker container ls -a`
![image](https://user-images.githubusercontent.com/4006603/117775509-e08b3980-b23a-11eb-917c-51df23b2c92f.png)

when I look at the logs:
`docker logs infallible_lalande`
![image](https://user-images.githubusercontent.com/4006603/117775674-04e71600-b23b-11eb-8de7-464da27ad6e4.png)

thank you

**Comment by scharissis** [comment]
Try specifying each of: db name, user name and password.
Test with user name "postgres" (the default)
Use latest postgres version that makes sense for you.

I do this by creating a dockertest.Pool, then dockertest.RunOptions (this is where I specify the above), then I launch the container with `pool.RunWithOptions`.

**Comment by nicklanng** [comment]
I wonder if this is related to the issue I'm seeing from today, since I updated Docker to 20.10.6.
Everything was working fine before this.

Here are the relevant logs from the tail of the postgres container.
```
server started

CREATE DATABASE

/usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*

2021-05-19 14:19:02.892 UTC [48] LOG: received fast shutdown request

waiting for server to shut down....2021-05-19 14:19:02.893 UTC [48] LOG: aborting any active transactions

2021-05-19 14:19:02.894 UTC [48] LOG: background worker "logical replication launcher" (PID 55) exited with exit code 1

2021-05-19 14:19:02.895 UTC [50] LOG: shutting down

2021-05-19 14:19:02.904 UTC [48] LOG: database system is shut down

done

server stopped

PostgreSQL init process complete; ready for start up.
```

It seems like Postgres creates the data volumes, then expects a restart.
I have no idea why the Docker version would cause this to start happening. Very odd!

**Comment by piusalfred** [comment]
> Try specifying each of: db name, user name and password.
> Test with user name "postgres" (the default)
> Use latest postgres version that makes sense for you.
> 
> I do this by creating a dockertest.Pool, then dockertest.RunOptions (this is where I specify the above), then I launch the container with `pool.RunWithOptions`.

How about a code snippet

**Comment by zfedoran** [comment]
@piusalfred / @azime not sure if you guys managed to fix this on your end but I also ran into this issue. See  https://github.com/ory/dockertest/pull/284 for an example that worked for me.

**Comment by aeneasr** [comment]
Closing this as it has been resolved in the examples
