### ISSUE TITLE
Feature request: Add support for API version 1.32+ for M1 mac users

### ISSUE THREAD

**Issue by applike-ss** [ory/dockertest#283]
**Is your feature request related to a problem? Please describe.**

We are facing a new problem with every new developer that wants to use a mac, since we settled on new generation devices and since those have the M1 apple silicon (arm64 based).
The issue occurs when our developers want to use ory/dockertest and specify an x86/x64 based image which is possible to run via `--platform` as specified here: https://docs.docker.com/engine/reference/commandline/run/

**Describe the solution you'd like**
I would like to see the 1.32 api integrated, so that we can specify the platform on the `RunOptions` and `BuildOptions`.

**Describe alternatives you've considered**
I didn't consider an alternative yet, because it seems logical to implement new api versions as they bring benefit.

**Additional context**
Apple M1 13" devices running macOs 11 are affected by this issue, likely more devices (chromebooks for example).

**Comment by aeneasr** [comment]
Unfortunately I do not have access to an M1 - but contributions are highly welcomed!

**Comment by applike-ss** [comment]
In fact i just read the documentation and i do not see where i would add a platform when sending the container create request. However in the listing of the containers it is obvious where it's put.
I read the v1.32 as well as the v1.41 (see https://docs.docker.com/engine/api/v1.41/#operation/ContainerCreate) and none of 'em seem to tell how to specify a platform.
Might dig into the docker client code later, obviously that must have a reference to that.
