### ISSUE TITLE
Cassandra Example

### ISSUE THREAD

**Issue by vtereso** [ory/dockertest#289]
**Describe the bug**

The Cassandra example does not work. I am not sure what has changed, but the session consistently errors within the retry with the following: `connect: connection refused`.

**To Reproduce**

Run the Cassandra Example. I believe all tags fail.

**Expected behavior**

A gocql session should be returned.

**Environment**

- Version: dockertest (github.com/ory/dockertest/v3) v3.7.0
- Environment: MacOS Big Sur (11.5.2), Docker (v20.10.7)

**Comment by vtereso** [comment]
The mount appears to be problematic: `Mounts:     []string{"/tmp/local-cassandra:/etc/cassandra"}`. Also, in older versions of gocql, the host lookup needs to be disabled:  `DisableInitialHostLookup`.

**Comment by vtereso** [comment]
Should I update the example with these changes?

**Comment by aeneasr** [comment]
Yes please!

**Comment by scortier** [comment]
@vtereso are you still facing the issue ? I think the mount is working perfectly fine , we don't need any changes in `cassandra` example .

@aeneasr If we have no further problem on this, then we can close the issue .
