### ISSUE TITLE
How to pass parameter in dockertest?

### ISSUE THREAD

**Issue by kokizzu** [ory/dockertest#308]
Use case: want to run PostgreSQL in memory instead of disk

https://stackoverflow.com/a/67509855/1620210
https://vladmihalcea.com/how-to-run-integration-tests-at-warp-speed-with-docker-and-tmpfs/

it needs to pass `--tmpfs=/data` for example.

How to pass those parameter to dockertest?

**Comment by kokizzu** [comment]
oh found it, there's `RunWithOptions`, but how to set the Tmpfs? what's the key and value of that map?
```
config.Tmpfs = map[string]string{`/var`:`rw`} // like this?
```

**Comment by ivanduka** [comment]
Hey @kokizzu, please share how you solved it :)

**Comment by kokizzu** [comment]
I forgot which project this was XD
can't find anything on my repo that states RunWithOptions

**Comment by kokizzu** [comment]
ah yes, that's how i do that previously:
https://github.com/search?q=RunWithOptions+TmpFs&type=code
