### ISSUE TITLE
GetBoundIP and GetHostPort don't return a host for rootless containers

### ISSUE THREAD

**Issue by uhthomas** [ory/dockertest#317]
**Describe the bug**

Podman does not assign rootless containers an IP. The ports are forwarded correctly and work as expected when using `localhost`, but the aforementioned functions return an empty string which leads to lookup failures.

**To Reproduce**

Install podman:

```sh
sudo apt install -y podman podman-docker
```

Start the user service (not sure if this is needed):

```sh
systemctl --user enable --now podman
```

Export the correct docker host environment variable to use the rootless podman socket:

```sh
export DOCKER_HOST="unix://$XDG_RUNTIME_DIR/podman/podman.sock"
```

Start a container using dockertest and observe a blank host, despite having a correctly forwarded port.

**Expected behavior**

GetBoundIP and GetHostPort should return "localhost".

**Environment**

- Version: github.com/ory/dockertest v3.3.5+incompatible
- Environment: Ubuntu 21.10 (impish)

**Additional context**

This works as expected when using rootfull containers and in general everything else works as expected.

**Comment by aeneasr** [comment]
Phew! No idea, pretty sure this is caused by dockertest using a pretty ancient version of the Docker client :/

**Comment by uhthomas** [comment]
To alleviate the problem, we wrote a wrapper around those two functions which assume that an empty host means the container is rootless. Not sure if this is the correct fix but thought it was worth sharing :)

```go
// getBoundIP gets the container's bound IP for the associated id.
//
// There is an upstream issue for rootless containers not returning an IP:
// https://github.com/ory/dockertest/issues/317
func getBoundIP(r *dockertest.Resource, id string) string {
	if ip := r.GetBoundIP(id); ip != "" {
		return ip
	}
	// If there is no bound IP, the container can be assumed to be rootless.
	// Rootless containers have their ports exposed on the host network.
	return "0.0.0.0"
}

// getHostPort gets the container's bound IP and port for the associated id, and
// joins them.
func getHostPort(r *dockertest.Resource, id string) string {
	if port := r.GetPort(id); port != "" {
		return net.JoinHostPort(getBoundIP(r, id), port)
	}
	// If there is no bound port for the container, mimic the upstream behaviour
	// of returning an empty string.
	return ""
}
```

**Comment by aeneasr** [comment]
Perfect, thanks!
