### ISSUE TITLE
BuildAndRun functions do not support container names different from the repository name

### ISSUE THREAD

**Issue by robertcankney** [ory/dockertest#330]
**Describe the bug**

[L329](https://github.com/ory/dockertest/blob/v3/dockertest.go#L331) in dockertest.go currently overwrites the values of RunOpts.Repository with the Name value for the container. This prevents BuildAndRunWithBuildOptions and any functions that call it from creating containers with a Name other than that of the repository, which in turn prevents multiple test packages from executing concurrently, as there is no way to set unique container names.

**To Reproduce**

**Expected behavior**

I'd expect repository to be honored if it is set - i.e. instead of 

```golang
runOpts.Repository = runOpts.Name
```

, something like

```golang
if runOpts.Repository == "" {
    runOpts.Repository = runOpts.Name
}
```

**Environment**

- Version: github.com/ory/dockertest/v3@v3.7.0
- Environment: All.

**Additional context**

More than happy to cut a PR for this!

**Comment by robertcankney** [comment]
Happy to make this change if repo owners agree with it - if so, would be great to get access to create a PR with this change. Would be super useful for our use of the package.

**Comment by aeneasr** [comment]
Yes, please do :) Please ensure that we keep backwards compatibility though! :)
