### ISSUE TITLE
Feature request: tmpfs volume and read-only volume mount

### ISSUE THREAD

**Issue by Warashi** [ory/dockertest#343]
**Is your feature request related to a problem? Please describe.**

A clear and concise description of what the problem is. Ex. I'm always
frustrated when MySQL container startup is slow.

**Describe the solution you'd like**

tmpfs volume mount for MySQL data volume would improve speed of startup.
and read-only mount for initial scripts directory would improve read throughput for initialize.

**Describe alternatives you've considered**

I don't considered alternative solutions.

**Additional context**

**Comment by Warashi** [comment]
sorry, I can use tmpfs and read-only volume mount if I use RunWithOptions with `func(*docker.HostConfig)`.
so, I close this issue.

**Comment by knightazura** [comment]
Hello @Warashi 
Can you give an example how to do that in your case?

I have similar case with you and until now, I can't find how to implement it.
Thank you.

**Comment by Warashi** [comment]
@knightazura 
in my case, code below works fine.
```go
	r, err = pool.RunWithOptions(runOptions, func(hc *docker.HostConfig) {
		hc.Mounts = append(hc.Mounts,
			docker.HostMount{
				Type:   "tmpfs",
				Target: "/var/lib/mysql",
			},
			docker.HostMount{
				Type:   "tmpfs",
				Target: "/var/log/mysql",
			},
		)
	})
```
