### ISSUE TITLE
update to runc 1.1.2

### ISSUE THREAD

**Issue by kokizzu** [ory/dockertest#357]
dependabot reporting CVE 

# Package / Affected versions / Patched version
github.com/opencontainers/runc (Go)
< 1.1.2
1.1.2

# Impact

A bug was found in runc where runc exec --cap executed processes with non-empty inheritable Linux process capabilities, creating an atypical Linux environment and enabling programs with inheritable file capabilities to elevate those capabilities to the permitted set during execve(2).

This bug did not affect the container security sandbox as the inheritable set never contained more capabilities than were included in the container's bounding set.
Patches

This bug has been fixed in runc 1.1.2. Users should update to this version as soon as possible.

This fix changes runc exec --cap behavior such that the additional capabilities granted to the process being executed (as specified via --cap arguments) do not include inheritable capabilities.

In addition, runc spec is changed to not set any inheritable capabilities in the created example OCI spec (config.json) file.

# Credits

The opencontainers project would like to thank [Andrew G. Morgan](https://github.com/AndrewGMorgan) for responsibly disclosing this issue in accordance with the [opencontainers org security policy](https://github.com/opencontainers/.github/blob/master/SECURITY.md).
For more information

If you have any questions or comments about this advisory:

    [Open an issue](https://github.com/opencontainers/runc/issues/new)
    Email us at [security@opencontainers.org](mailto:security@opencontainers.org) if you think you’ve found a security bug

**Comment by kokizzu** [comment]
https://github.com/ory/dockertest/pull/355

**Comment by kokizzu** [comment]
please release a new version :3

**Comment by aeneasr** [comment]
you can use go.mod rewrites if a version is not released, but i'll of course do that :)
