### ISSUE TITLE
DOC: "go" and "dep" unknown

### ISSUE THREAD

**Issue by buhtz** [ory/dockertest#360]
The section **Installing and using Dockertest** in the `README.md` show the two commands (?) `go` and `dep`.

They are not installed by default on Debian and I assume Windows also. I know both of them are not "the world". ;)

It would be nice for some of the new users if you could add a small footnote to explain what go and dep are. This would make it easier to install them.

**Comment by aeneasr** [comment]
PRs welcoemd

**Comment by buhtz** [comment]
I see contributors are not welcome to you if you answer so inpolit.

I don't have to defend my self why I don't create a PR for that.
Also you don't have to defend yourself why you don't.

Take a step outside of your bubble and imagine that maybe I am one of that described users. I don't know what go and dep is and I don't have the expertise to describe it so far.

I just tried to help to improve your project. This wasn't only a support question but just a hint how you can make things better for your users.

**Comment by aeneasr** [comment]
There was no intention to offend you, the easiest way to fix things is to contribute changes when requesting them.

In general though, this library is a testing utility for writing better Go tests. If users don't have Go installed, this library won't be needed as it is a targeted use case and requires at least some knowledge of Go beforehand to be useful.
