### ISSUE TITLE
Forum link is dead

### ISSUE THREAD

**Issue by buhtz** [ory/dockertest#361]
https://github.com/ory/dockertest/blob/7b2512856bc26173841ee4a13a46755dc5d08ba4/.github/ISSUE_TEMPLATE/config.yml#L4

That link to the forum is dead.

**Comment by aeneasr** [comment]
@vinckr i think this needs an update in ory/meta, without breaking for the projects that do have their own discussions? Can you PTAL when you have time?

**Comment by buhtz** [comment]
I don't see this fixed. The forum link still gives me a 404.
https://github.com/ory/dockertest/issues/new/choose

**Comment by vinckr** [comment]
Hey, 
the change is live but the updating CI is failing (for a [different reason](https://github.com/ory/meta/issues/146)). 
Once that is fixed, this should be resolved.

Thanks for reporting!

**Comment by buhtz** [comment]
I wasn't aware that a CI is behind it and that this is a job for a CI.
No matter. ;) I don't have to understand everything.

**Comment by vinckr** [comment]
has been fixed since, just forgot to close the issue. 
FYI, I cant moderate in fosite @aeneasr
