### ISSUE TITLE
Pool.Run should not error if container exists

### ISSUE THREAD

**Issue by pjebs** [ory/dockertest#373]
I have  a build script that runs multiple tests in parallel. They appear to be connecting to the same docker host.

All the tests have a `TestMain`, which creates a Kafka container and then the test attempts to connect to it (via `pool.Run`).

Currently because the kafka container exists, when some of the tests run, I get an error `could not start zookeeper: : container already exists` from the `Pool.Run` function.

I think `Pool.Run` should at least give a setting so that if the container exists, it can connect to it instead of try to create a new container.

How can I solve this issue?

**Comment by tmirun** [comment]
same question
