### ISSUE TITLE
Cannot find /var/run/docker.sock on Mac/Windows

### ISSUE THREAD

**Issue by tsawler** [ory/dockertest#413]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/dockertest/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/dockertest/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

When attempting to bring up Postgres using ory, I get this error on Mac OS X 13.2.1 with Docker Desktop 4.17.0 (99724). I get the same error on Windows 11:

 Could not start resource: : dial unix /var/run/docker.sock: connect: no such file or directory

Here is a minimal code example:

~~~
package data

import (
	"database/sql"
	"fmt"
	_ "github.com/jackc/pgconn"
	_ "github.com/jackc/pgx/v4"
	_ "github.com/jackc/pgx/v4/stdlib"
	"github.com/ory/dockertest/v3"
	"github.com/ory/dockertest/v3/docker"
	"log"
	"os"
	"testing"
)


var (
	host     = "localhost"
	user     = "postgres"
	password = "secret"
	dbName   = "mydb"
	port     = "5435"
	dsn      = "host=%s port=%s user=%s password=%s dbname=%s sslmode=disable timezone=UTC connect_timeout=5"
)

var testDB *sql.DB
var resource *dockertest.Resource
var pool *dockertest.Pool

func TestMain(m *testing.M) {
	p, err := dockertest.NewPool("")
	if err != nil {
		log.Fatalf("could not connect to docker: %s", err)
	}

	pool = p

	opts := dockertest.RunOptions{
		Repository: "postgres",
		Tag:        "14.2",
		Env: []string{
			"POSTGRES_USER=" + user,
			"POSTGRES_PASSWORD=" + password,
			"POSTGRES_DB=" + dbName,
		},
		ExposedPorts: []string{"5432"},
		PortBindings: map[docker.Port][]docker.PortBinding{
			"5432": {
				{HostIP: "0.0.0.0", HostPort: port},
			},
		},
	}

	resource, err = pool.RunWithOptions(&opts)
	if err != nil {
		log.Println(err)
		//_ = pool.Purge(resource)
		log.Fatalf("could not start resource: %s", err)
	}

	if err := pool.Retry(func() error {
		var err error
		testDB, err = sql.Open("pgx", fmt.Sprintf(dsn, host, port, user, password, dbName))
		if err != nil {
			log.Println("Error:", err)
			return err
		}
		return testDB.Ping()
	}); err != nil {
		_ = pool.Purge(resource)
		log.Fatalf("could not connect to docker: %s", err)
	}

	code := m.Run()

	if err := pool.Purge(resource); err != nil {
		log.Fatalf("could not purge resource: %s", err)
	}

	os.Exit(code)
}
~~~

This code ran without a problem prior to the latest docker desktop update. I'm not sure how to resolve the issue. Any help would be much appreciated.

### Reproducing the bug

With the code above, run go test -v .

### Relevant log output

```shell
% go test -v .
2023/03/07 09:21:37 Could not start resource: : dial unix /var/run/docker.sock: connect: no such file or directory
FAIL    vue-api/internal/data   0.602s
FAIL
```

### Version

v3.9.1

### On which operating system are you observing this issue?

macOS

### In which environment are you deploying?

Docker

**Comment by Atixx** [comment]
A workaround that I've been using is to symlink the expected location to the actual one, which changes from `/var/run` to `~/.docker/run`.

You can do that by running `sudo ln -s ~/.docker/run/docker.sock /var/run`

If in your case the socket is in a different spot, make sure to change the origin of that link

**Comment by tsawler** [comment]
Another option (and it's the one I ultimately went with) was to move over to [testcontainers/testcontainers-go](https://github.com/testcontainers/testcontainers-go).

**Comment by pmrt** [comment]
Just wanted to note that you don't need to create symbolic links every time you run docker if you're using docker destop. In the last version there's an option for this in Docker Desktop > Settings > Advanced:

![Screen Shot 2023-07-20 at 11 59 48](https://github.com/ory/dockertest/assets/22831717/c3c46f8e-d8e1-41e9-9c34-f62441a5a283)

So I'm not sure whether we should consider this a bug or is it just that docker added an extra layer of security. Either way this should be documented.

**Comment by YoEight** [comment]
Greetings,

I got the same issue on Linux too (not running on Windows nor Mac). I think the library assuming the current user can run docker rootless is a bug. Using Docker Desktop is the recommended way now even on Linux. It allows the current user to use docker rootless, without compromising security.

The option suggested by @pmrt is not available on Docker Desktop linux unfortunately

Thanks for your time
