### ISSUE TITLE
Tests fail without internet access

### ISSUE THREAD

**Issue by LewisWatson** [ory/dockertest#70]
Hello,

I noticed that my tests fail when run offline. This might be due to [Pool.Run](https://github.com/ory-am/dockertest/blob/v3.0.3/dockertest.go#L73) being coded to do always do a pull, even when the image is already downloaded.

**Comment by aeneasr** [comment]
Thanks! This explains also why the tests are much slower now.

**Comment by LewisWatson** [comment]
Great! That fixed it and has also resulted in a noticeable speed improvement.

Thanks.
