### ISSUE TITLE
ConnectToMongoDB undefined in in v3

### ISSUE THREAD

**Issue by drasko** [ory/dockertest#73]
I'm getting `undefined: dockertest.ConnectToMongoDB`. Does support for MongoDB exists in v3?

**Comment by aeneasr** [comment]
Yes, MongoDB is supported. In fact, all docker images are now supported! You simply specify the image and the port and then you're good to go. Check out how this works with, for example, MySQL: https://github.com/ory-am/dockertest/blob/v3/dockertest_test.go#L28-L40

Here are more examples: https://github.com/ory-am/common/blob/master/integration/integration.go

**Comment by drasko** [comment]
Thanks, this worked for me: https://github.com/mainflux/mainflux-core/blob/master/api/init_test.go

It would be great if you can add MongoDB example similar to this implementation to your https://github.com/ory-am/common/blob/master/integration/integration.go, so that everybody can have a reference.

**Comment by aeneasr** [comment]
Hi, the API changed completely. You no longer need those hard dependencies. Did you check the examples I provided? Running MongoDB should be as easy as:

```go

	pool, err = dockertest.NewPool("")
	if err != nil {
		log.Fatalf("Could not connect to docker: %s", err)
	}

	resource, err := pool.Run("mongo", "3.0", []string{""})
	if err != nil {
		log.Fatalf("Could not start resource: %s", err)
	}

	mongoUrl := fmt.Sprintf("mongodb://localhost:%s", resource.GetPort("27017/tcp"))

	// connect to mongo here
```

**Comment by drasko** [comment]
Which hard dependencies? My implementation (in the link I posted) is almost identical to the one you posted here... Now I'm confused :(

**Comment by aeneasr** [comment]
Ah sorry, it was late and I think I misread :) The link you provided looks perfect! We could probably add some examples in the README or have a dedicated `docs/` directory for the different databases?

What I meant with the hard dependencies is that now `go get github.com/ory-am/dockertest` won't pull all those drivers (mysql, postgres, etcd, ...) any more, which is I think a really cool thing :)
