### ISSUE TITLE
Support for specifying mounts in v3 of the api

### ISSUE THREAD

**Issue by briankassouf** [ory/dockertest#75]
In v2 of the api the `ConnectToCassandra` function took a `optionalParams` parameter. Using this parameter I was able to create a mount with a custom cassandra config. 

It would be nice for this same functionality to exist in v3.

**Comment by aeneasr** [comment]
What type of parameters did you pass along?

**Comment by briankassouf** [comment]
I was passing in a volume option:

```
dockertest.ConnectToCassandra("latest", 60, 1000*time.Millisecond, func(connURL string) bool {},[]string{"-v", cwd + "/test-fixtures/:/etc/cassandra/"}...)
```

**Comment by aeneasr** [comment]
Do you know if you can pass those via environment variables?

**Comment by aeneasr** [comment]
Closing, see #87
