### ISSUE TITLE
Example not working: newPool not found

### ISSUE THREAD

**Issue by Kliton** [ory/dockertest#76]
<img width="882" alt="schermata 2017-01-24 alle 22 31 20" src="https://cloud.githubusercontent.com/assets/10452377/22267651/e818c60c-e284-11e6-9fc4-ed0e33b8e138.png">

How to solve this?

**Comment by Kliton** [comment]
Ps. I have copied the code from the example in the readme.

**Comment by aeneasr** [comment]
https://github.com/ory-am/dockertest/blob/v3/dockertest.go#L44

**Comment by aeneasr** [comment]
I can't reproduce this, please check if you have in fact an up-to-date version of dockertest, you can do so with: `go get -u gopkg.in/ory-am/dockertest.v3`
