### ISSUE TITLE
Not working after docker 1.13.1 update

### ISSUE THREAD

**Issue by rif** [ory/dockertest#79]
I have this code that was working before today's docker update:
```go
        resource, err := pool.Run("mongo", "latest", []string{""})
	if err != nil {
		log.Fatalf("Could not start resource: %s", err)
	}
```
Starting today I get: 2017/02/13 14:07:21 Could not start resource: : API error (500): {"message":"invalid environment variable: "}

Docker version:
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3727
 Built:        Sun Feb 12 02:40:56 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3727
 Built:        Sun Feb 12 02:40:56 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Comment by aeneasr** [comment]
You're providing an empty environment variable (`[]string{""}`) either pass an empty slice or nil

**Comment by rif** [comment]
thanks, that was it :)

**Comment by rif** [comment]
I guess we hit a record on the shortest github issue 🥇

**Comment by aeneasr** [comment]
;)
