### ISSUE TITLE
Starting mongo on OSX results in error

### ISSUE THREAD

**Issue by olbrichj** [ory/dockertest#84]
When trying the provided example, it returns this error:

Could not start resource: : API error (500): {"message":"invalid environment variable: "}

Using the official CE-Docker for Mac

docker version:
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:40:59 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 07:52:04 2017
 OS/Arch:      linux/amd64
 Experimental: true

**Comment by aeneasr** [comment]
What image are you trying to start?

**Comment by olbrichj** [comment]
mongo

I've copied the example and changed the sql part to mongo

resource, err := pool.Run("mongo", "3.0", []string{""})

**Comment by aeneasr** [comment]
You're setting an empty env var which causes the error, try nil or string{} instead. Please provide a PR if this is wrong in the docs :)

**Comment by olbrichj** [comment]
you just have to pass nil

resource, err := pool.Run("mongo", "3.0", nil)

Will try to create a PR
